services:
    hifikabin.stickybar.listener:
        class: hifikabin\stickybar\event\listener
        arguments:
            - @user
            - @template
            - @config
        tags:
            - { name: event.listener }
    hifikabin.stickybar.ucp_listener:
        class: hifikabin\stickybar\event\ucp_listener
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }